services:
  - type: web
    name: meesho-poster-bot
    runtime: python
    buildCommand: pip install -r requirements.txt && playwright install --with-deps chromium
    startCommand: python bot.py
    plan: free
    healthCheckPath: /health
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: viralbots
      - key: DEAL_CHANNEL_ID
        sync: false
